import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Products from "@/components/Products";

import products from "../data/products";

export default function Home() {
  console.log("products", products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div>
          <Navbar />
        </div>
        <div>
          <Hero />
        </div>
        <div className={styles.products_title}>
          <h2>Trenading Products</h2>
        </div>
        <div>
          <Products />
        </div>
        <div></div>
      </div>
    </div>
  );
}
