import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";

import products from "../data/products";

export default function Home() {
  console.log("products", products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div>
          <Navbar />
        </div>
        <div>
          <Hero />
        </div>
        <div>
          <div className={styles.products_title}>
            <h2>Trenading Products</h2>
          </div>
          <div className={styles.products_grid_container}>
            {products.map((product) => {
              const { id, title, image, price } = product;
              return (
                <div key={id} className={styles.product_card}>
                  <div className={styles.card_img_container}>
                    <Image src={image} alt={title} width={427} height={420} />
                  </div>
                  <div>
                    <h4>{title}</h4>
                  </div>
                  <div>
                    <h5>{price}</h5>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
